version: '2'
services:
  mapas:
    build:
      context: ../
      dockerfile: compose/local/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ../docker-data/assets:/var/www/html/assets
      - ../docker-data/public-files:/var/www/html/files
      - ../docker-data/private-files:/var/www/private-files
      - ../docker-data/pcache-cron.log:/var/www/scripts/nohup.out

      - ../compose/common/config.d:/var/www/html/protected/application/conf/conf-common.d
      - ../compose/local/config.d:/var/www/html/protected/application/conf/config.d
      - ../compose/common/config-csv-inciso1.php:/var/www/html/protected/application/plugins/AldirBlancDataprev/config-csv-inciso1.php
      - ../compose/common/config-csv-inciso2.php:/var/www/html/protected/application/plugins/AldirBlancDataprev/config-csv-inciso2.php
      # themes and plugins
      ##- ../themes/MapasComBr:/var/www/html/protected/application/themes/MapasComBr
      - ../themes/MatoGrossoSul:/var/www/html/protected/application/themes/MatoGrossoSul
      - ../plugins/AldirBlanc:/var/www/html/protected/application/plugins/AldirBlanc
      - ../plugins/MultipleLocalAuth:/var/www/html/protected/application/plugins/MultipleLocalAuth
      - ../plugins/SamplePlugin:/var/www/html/protected/application/plugins/SamplePlugin
      - ../plugins/AldirBlancRedirects:/var/www/html/protected/application/plugins/AldirBlancRedirects

    environment:
      - PENDING_PCACHE_RECREATION_INTERVAL=10
      - APP_MODE=development

    depends_on:
      - db
  
    stdin_open: true
    tty: true

  db:
    image: mdillon/postgis:10
    environment:
      - POSTGRES_PASSWORD=mapas
      - POSTGRES_USER=mapas
      - POSTGRES_DB=mapas
    ports:
      - "5432:5432"
    volumes:
      - ../compose/local/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - ../docker-data/db-data:/var/lib/postgresql/data

volumes:
  db-data: